name: Extract Pull PR and DE number on merge

on: 
  pull_request: 
    types: [closed] 
    branches: 
      - master
    # Only trigger the workflow if the pull request is merged 
    # Use the "pull_request.merged" property to check if the pull request is merged 
    # Use the "if" expression to conditionally execute the job 
   
jobs: 
  extract_pr_us: 
    runs-on: windows-latest 
    if: github.event.pull_request.merged == true 
    steps: 
      - name: Get Pull Request URL 
        id: pr_url 
        run: | 
          echo "::set-output name=url::${{ github.event.pull_request.html_url }}" 

      - name: Get Source Branch Name 
        id: source_branch 
        run: | 
          echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}" 

      - name: Get Pull Request Number 
        id: pr_number 
        run: | 
          echo "::set-output name=number::${{ github.event.pull_request.number }}" 

      - name: Defect Us Number 
        id: Us_number
        run: | 
          branch_name=${{ github.event.pull_request.head.ref }} 
          $Us_number = ($branch_name -split '/')[1] -split '_')[0]
          echo "::set-output name= Us_number ::$Us_number" 

      - name: Use Pull Request URL, Branch Name, and Number 
        run: | 
          echo "Pull Request URL: ${{ steps.pr_url.outputs.url }}" 
          echo "Source Branch Name: ${{ steps.source_branch.outputs.branch }}" 
          echo "Pull Request Number: ${{ steps.pr_number.outputs.number }}" 
          echo "US Number: ${{ steps.Us_number.outputs.Us_number }}" 

 
