name: Extract Pull PR and DE number on merge

on:
 push:
  branches:
   - master

jobs:
 extract_Us_Pr_Number:
  runs-on: windows-latest
  steps:
   - name: Extract User Story Number and PR Url
     run: | 
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}" 
          for /f "tokens=2 delims=_" %%i in ("${{ github.event.pull_request.head.ref }}") do set source_branch=%%i 
          echo "Source Branch: %source_branch%" 
          echo "::set-output name=pr_url::${{ github.event.pull_request.html_url }}" 
          echo "::set-output name=source_branch::%source_branch%" 

  outputs: 
      pr_url: ${{ steps.extract_Us_Pr_Number.outputs.pr_url }} 
      source_branch: ${{ steps.extract_Us_Pr_Number.outputs.source_branch}} 

        
      
